###Import OTU table into R for analysis
I am using R version 4.0.4 (2021-02-15)
Now the newly created and modified metagenome (or bacteria, archaea, eukarya, virus) file can be imported into R for analysis 
```{r}
library(propr)
library(magrittr)
library(zCompositions)
library(dplyr)
library(ggplot2)
library(tidyverse) 
library(readr)
library(mixOmics)
library(selbal)
library(vegan)
library(scales)
library(ggthemes)
require(gtools)
library(viridis)
library(ggpubr)
library(corrplot)
library(psych)
library(rstatix)
library(png)
library(grid)
library(gridExtra)
library(cowplot)
library(data.table)
```
```{r}
# read in OTU table and mapping file
metagen_OTU <- read.csv('../../data/Diversity_Analysis/input/metagenomemodified.csv',sep=',',row.names = 1,header = 1,check.names=FALSE)
map <- read.table('../../data/Diversity_Analysis/input/TJRIVER_mappingfile.txt',sep='\t',header =1,row.names = 1)
```
```{r}
#To reduce the overall number of variables if desired.
metagen_1 <- metagen_OTU[rowSums(metagen_OTU <1) <= 0.01 * ncol(metagen_OTU), ]
metagen_5 <- metagen_OTU[rowSums(metagen_OTU <1) <= 0.05 * ncol(metagen_OTU), ]
metagen_8 <- metagen_OTU[rowSums(metagen_OTU <1) <= 0.08 * ncol(metagen_OTU), ]
metagen_10 <- metagen_OTU[rowSums(metagen_OTU <1) <= 0.10 * ncol(metagen_OTU), ]
metagen_50 <- metagen_OTU[rowSums(metagen_OTU <1) <= 0.50 * ncol(metagen_OTU), ]
metagen_100 <- metagen_OTU[rowSums(metagen_OTU <1) <= 1.00 * ncol(metagen_OTU), ]
```
```{r}
#Check for number of 0s in sample
table(metagen_OTU == 0)
```
```{r}
#replace 0s with p-counts
metagen_z <- cmultRepl((metagen_OTU), output = 'p-counts')
```
```{r}
#Check to see if 0s have been removed
table(metagen_z == 0)
```
```{r}
#Transpose for clr
metagen_z_t <- t(metagen_z)
```
```{r}
#define clr function
clr <- function(x) sweep(log(x), 1, rowMeans(log(x)), "-")
```
```{r}
#Perform clr
metagen_clr_t <- clr(metagen_z_t)
```
```{r}
#transpose back
metagen_clr <- t(metagen_clr_t)
```
```{r}
#Create dataframes and order them and map by ID
metagen_clr_df <- as.data.frame(metagen_clr)
metagen_clr_ordered <- metagen_clr_df[order(row.names(metagen_clr_df)), order(colnames(metagen_clr_df))]
map_ordered <- map[order(row.names(map)),order(colnames(map))]
```
```{r}
#Write out clr file
write.csv(metagen_clr_ordered, "../../data/Diversity_Analysis/output/TJ_River_metagen_clr.csv")
```
```{r}
#Filter out anything not on mapping file
metagen_clr_filtered <- metagen_clr_ordered[,row.names(map_ordered)]
```
```{r}
#Transpose data
metagen_clr_filtered_t <- t(metagen_clr_filtered)
```
```{r}
#Make matrix
metagen_clr_m <- as.matrix(metagen_clr_filtered_t)
```
```{r}
#Make NMDS data
metagen_nmds = metaMDS(metagen_clr_m, distance = 'euclidean')
```
```{r}
#Extract NMDS data
metagen_scores = as.data.frame(scores(metagen_nmds))
```
```{r}
#Add mapping file columns to NMDS data
metagen_scores$date = as.factor(map_ordered$date)
metagen_scores$number = as.factor(map_ordered$number)
metagen_scores$site = as.factor(map_ordered$site)
```
```{r}
#plot NMDS adjust aes according to data
metagen_nmdsplot <- ggplot(metagen_scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(size = 3, aes(colour = site, shape = date))+ 
  geom_text(data = metagen_scores,aes(x=NMDS1,y=NMDS2,label=number),size=2,vjust=2)+
  ggtitle('Metagenomic NMDS')+
  theme(
    plot.title = element_text(color="black", size=10, face="bold"),
    panel.background = element_rect(fill = "white",
                                    colour = "black",
                                    size = 0.5, linetype = "solid"),
  )
```
```{r}
#show plot
printplot <- ggpubr::ggarrange(metagen_nmdsplot,ncol = 1,nrow=1,labels = c("A"))
printplot
```
```{r}
ggsave('../../data/Diversity_Analysis/output/NMDS_TJ_River_metagen.png', width=6.5, height=4,plot=metagen_nmdsplot)
```
```{r}
#Vegdist
metag_dist<-vegdist(metagen_clr_filtered_t, method='euclidian')
```
```{r}
#adonis
metag_site <- adonis2(metag_dist~site, data=map_ordered, permutations = 9999, method = "euclidian")
metag_date <- adonis2(metag_dist~date, data=map_ordered, permutations = 9999, method = "euclidian")
metag_number <- adonis2(metag_dist~number, data=map_ordered, permutations = 9999, method = "euclidian")
```
```{r}
capture.output(metag_site,file="../../data/Diversity_Analysis/output/TJ_River_site_permanova_10000.csv")
capture.output(metag_date,file="../../data/Diversity_Analysis/output/TJ_River_date_permanova_10000.csv")
capture.output(metag_number,file="../../data/Diversity_Analysis/output/TJ_River_number_permanova_10000.csv")
```
```{r}
site_metagen <- factor(map_ordered[colnames(metagen_clr_filtered),]$site)
date_metagen <- factor(map_ordered[colnames(metagen_clr_filtered),]$date)
number_metagen <- factor(map_ordered[colnames(metagen_clr_filtered),]$number)
```
```{r}
metagbeta_clr_site <- betadisper(metag_dist, site_metagen)
metagbetadispr_site <- permutest(metagbeta_clr_site)
metagdistances_site <- data.frame(metagbeta_clr_site[['distances']])
metagdistances_site <- cbind (metagdistances_site, site_metagen)
colnames(metagdistances_site) <- c('Distance_to_Centroid', 'site')
```
```{r}
metagbeta_clr_date <- betadisper(metag_dist, date_metagen)
metagbetadispr_date <- permutest(metagbeta_clr_date)
metagdistances_date <- data.frame(metagbeta_clr_date[['distances']])
metagdistances_date <- cbind (metagdistances_date, date_metagen)
colnames(metagdistances_date) <- c('Distance_to_Centroid', 'date')
```
```{r}
dist_microbe_box_site <- ggboxplot(metagdistances_site, x = "site", y = "Distance_to_Centroid" , add = "point")
dist_microbe_box_site
dist_site_tukey <- TukeyHSD(metagbeta_clr_site)
microbe_site_tuk <- data.frame(dist_site_tukey[['group']])
write.csv(microbe_site_tuk, "../../data/Diversity_Analysis/output/clr_betadispr_site_tukey.csv")
ggsave('../../data/Diversity_Analysis/output/clr_betadispr_box_site.png',width=12, height=4, plot = dist_microbe_box_site)
```
```{r}
dist_microbe_box_date <- ggboxplot(metagdistances_date, x = "date", y = "Distance_to_Centroid" , add = "point")
dist_microbe_box_date
dist_date_tukey <- TukeyHSD(metagbeta_clr_date)
microbe_date_tuk <- data.frame(dist_date_tukey[['group']])
write.csv(microbe_date_tuk, "../../data/Diversity_Analysis/output/clr_betadispr_date_tukey.csv")
ggsave('../../data/Diversity_Analysis/output/clr_betadispr_box_date.png',width=12, height=4, plot = dist_microbe_box_date)
```
```{r}
betadipsr_figure_site_date <- ggarrange(dist_microbe_box_site,dist_microbe_box_date,
                                    labels = c("A", "B"),
                                    ncol = 1, nrow = 2)
betadipsr_figure_site_date
```
```{r}
ggsave('../../data/Diversity_Analysis/output/clr_betadispr_boxplot_site_date.png',width=15, height=8, plot = betadipsr_figure_site_date)
```